# Generated by Django 3.2 on 2022-05-29 15:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=datetime.datetime(2022, 5, 29, 15, 17, 56, 137657, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
