# Generated by Django 3.2 on 2022-05-30 03:47

import ckeditor.fields
import datetime
from django.db import migrations
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='body',
            field=ckeditor.fields.RichTextField(default=datetime.datetime(2022, 5, 30, 3, 47, 32, 772087, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
