# Generated by Django 3.2 on 2022-05-30 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220530_0350'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='image',
            new_name='thumbnail',
        ),
    ]
