# Generated by Django 3.2 on 2022-05-30 04:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20220530_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 4, 42, 35, 932753, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
