# Generated by Django 3.2 on 2023-01-11 17:00

from django.db import migrations, models
import testimonial.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_iamge', models.ImageField(upload_to=testimonial.models.upload_path)),
                ('name', models.CharField(max_length=80)),
                ('job_position', models.CharField(max_length=80)),
                ('description', models.TextField(max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
