# Generated by Django 3.2 on 2022-08-31 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0002_alter_testimonial_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='date',
        ),
    ]
