# Generated by Django 3.2 on 2022-09-05 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0003_remove_testimonial_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='social_media_address',
        ),
    ]
