# Generated by Django 3.2 on 2023-01-11 17:00

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('data_filter', models.CharField(help_text='change fild name space to hiphen', max_length=128)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iamge', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=80)),
                ('short_description', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('customer_opinion', models.CharField(max_length=300)),
                ('date', models.DateTimeField()),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.branch')),
            ],
        ),
    ]
