# Generated by Django 3.2 on 2023-01-01 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20221230_1400'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PortfolioDescription',
            new_name='Portfolio',
        ),
    ]
