# Generated by Django 3.2 on 2023-01-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_portfoliodescription_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='data_filter',
            field=models.CharField(default='opensource', help_text='change fild name space to hiphen', max_length=128),
            preserve_default=False,
        ),
    ]
