# Generated by Django 3.2 on 2023-01-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(default='slug-for-portfolio', max_length=200),
            preserve_default=False,
        ),
    ]
