# Generated by Django 3.2 on 2022-05-27 11:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 11, 11, 28, 199921, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
