# Generated by Django 3.2 on 2022-06-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_video_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=120)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
