# Generated by Django 3.2 on 2022-06-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_connectme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectme',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
