# Generated by Django 3.2 on 2022-06-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_connectme_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectme',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
