# Generated by Django 3.2 on 2022-09-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_i_am', models.TextField(max_length=600)),
                ('my_vision', models.TextField(max_length=600)),
                ('my_history', models.TextField(max_length=600)),
            ],
        ),
    ]
