# Generated by Django 3.2 on 2022-09-15 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_mystory'),
    ]

    operations = [
        migrations.AddField(
            model_name='mystory',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
