# Generated by Django 3.2 on 2022-09-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_mystory_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mystory',
            name='my_history',
            field=models.TextField(max_length=490),
        ),
        migrations.AlterField(
            model_name='mystory',
            name='my_vision',
            field=models.TextField(max_length=490),
        ),
        migrations.AlterField(
            model_name='mystory',
            name='who_i_am',
            field=models.TextField(max_length=490),
        ),
    ]
