# Generated by Django 3.2 on 2022-09-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('links', models.URLField()),
                ('color', models.CharField(max_length=8)),
                ('discription', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
