name: deploy

on:
  workflow_run:
    workflows: ["test"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: echo "deploy"