name: test

on: [pull_request, push]

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - run: pip3 install -r requirements.txt
      - run: python3 app/manage.py test --settings=config.settings.development

