name: test

on: [pull_request, push]

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: pip3 install -r requirements.txt
      - name: Run test
        run: python3 app/manage.py test --settings=config.settings.development

